name: Terraform2

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  terraform:
    uses: ElStepanyan/actions-test/.github/workflows/terraform.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  docker:
    uses: ElStepanyan/actions-test/.github/workflows/docker.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - terraform
  Custom-Action:
     uses: ElStepanyan/actions-test/.github/workflows/test-custom-action.yml@main
     needs:
       - docker



