name: Terraform2

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  terraform:
    uses: ElStepanyan/actions-test/.github/workflows/terraform.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

